version: 2
updates:
- package-ecosystem: nuget
  directory: "/Source"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  target-branch: main
  labels:
  - ":heavy_check_mark: dependencies"
  milestone:
  - "next-release"
