image: Visual Studio 2022
branches:
  only:
    - main
configuration: Release
platform: x64
build_script:
  - ps: |
      .\build.ps1   

#install:
#  - git submodule update --init
#before_build:
#  - dotnet restore .\Source\NETworkManager.sln
#build_script:
#  - dotnet build .\Source\NETworkManager.sln --configuration Release --no-restore
