version: 2.0.{build}
image: Visual Studio 2019
branches:
  only:
   - master
   - net5-develop
configuration: Release
platform: x64
before_build:
  - nuget restore
   #- MSBuild -t:restore .\Source\NETworkManager\NETworkManager.csproj
install:
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
  - ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -Version "5.0.100-preview.8.20417.9" -InstallDir "$env:ProgramFiles\dotnet"'