# Created using WinGet Automation (CLI)

# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: BornToBeRoot.NETworkManager
PackageVersion: 2024.5.27.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BornToBeRoot/NETworkManager/releases/download/2024.5.27.0/NETworkManager_2024.5.27.0_Setup.msi
  InstallerSha256: be6a466acd8912b21702a8d07cc45d7def7d177a6bfc3bde2ab97e1dbe8e9cea
ProductCode: '{e343d8ab-ed71-41d1-9784-6f6860bda078}'
ManifestType: installer
ManifestVersion: 1.5.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: "2024-05-27"
