PackageIdentifier: BornToBeRoot.NETworkManager
PackageVersion: 2021.9.5.0
PackageName: NETworkManager
Publisher: BornToBeRoot
ShortDescription: A powerful tool for managing networks and troubleshoot network problems!
PackageUrl: https://borntoberoot.net/NETworkManager
License: GNU General Public License v3.0
LicenseUrl: https://github.com/BornToBeRoot/NETworkManager/blob/master/LICENSE
Moniker: networkmanager
Tags: 
- wifi
- ipscanner
- portscanner
- traceroute
- pingmonitor
- dns
- remotedesktop
- putty
- lldp
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BornToBeRoot/NETworkManager/releases/download/2021.9.5.0/NETworkManager_2021.9.5.0_Setup.exe
  InstallerType: inno
  InstallerSha256: 883188AD58FB936FCA82846A261840F67E19734C20093996CBCDA75F4CE41EAA
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
