PackageIdentifier: BornToBeRoot.NETworkManager
PackageVersion: 2021.11.30.0
PackageName: NETworkManager
Publisher: BornToBeRoot
ShortDescription: A powerful tool for managing networks and troubleshoot network problems!
PackageUrl: https://borntoberoot.net/NETworkManager
License: GNU General Public License v3.0
LicenseUrl: https://github.com/BornToBeRoot/NETworkManager/blob/main/LICENSE
Moniker: networkmanager
Tags: 
- wifi
- ipscanner
- portscanner
- traceroute
- pingmonitor
- dns
- remotedesktop
- putty
- lldp
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BornToBeRoot/NETworkManager/releases/download/2021.11.30.0/NETworkManager_2021.11.30.0_Setup.exe
  InstallerType: inno
  InstallerSha256: AFDA99002A95D78127A26ADCED00F1A86DCBDB6DA0782A761088FFBF3BFF1DF9
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
